const images = [
  {
    id: "1",
    name: "chain",
    cost: "5",
    src: require("./assets/chain.png"),
    x: 158,
    y: 45,
    height: 100,
    width: 70,
  },
  {
    id: "2",
    name: "propeller",
    cost: "10",
    src: require("./assets/propeller.png"),
    x: 150,
    y: -10,
    height: 100,
    width: 100,
  },
  {
    id: "3",
    name: "shades",
    cost: "4",
    src: require("./assets/shades.png"),
    x: 160,
    y: 67,
    height: 20,
    width: 80,
  },
  {
    id: "5",
    name: "ironman",
    cost: "8",
    src: require("./assets/ironman.png"),
    x: 110,
    y: 30,
    height: 100,
    width: 160,
  },
  {
    id: "6",
    name: "bunnyears",
    cost: "8",
    src: require("./assets/bunnyears.png"),
    x: 140,
    y: -33,
    height: 100,
    width: 100,
  },
  {
    id: "7",
    name: "crown",
    cost: "8",
    src: require("./assets/crown.png"),
    x: 155,
    y: 0,
    height: 75,
    width: 75,
  },
  {
    id: "8",
    name: "bow",
    cost: "8",
    src: require("./assets/bow.png"),
    x: 137,
    y: 0,
    height: 100,
    width: 100,
  },
  {
    id: "9",
    name: "tie",
    cost: "8",
    src: require("./assets/tie.png"),
    x: 140,
    y: 115,
    height: 100,
    width: 100,
  },
  {
    id: "10",
    name: "fedora",
    cost: "8",
    src: require("./assets/fedora.png"),
    x: 140,
    y: -10,
    height: 100,
    width: 100,
  },
  {
    id: "11",
    name: "bandana",
    cost: "8",
    src: require("./assets/bandana.png"),
    x: 149,
    y: 95,
    height: 100,
    width: 100,
  },
  {
    id: "12",
    name: "batman",
    cost: "8",
    src: require("./assets/batman.png"),
    x: 108,
    y: -5,
    height: 155,
    width: 155,
  },
  {
    id: "14",
    name: "banana",
    cost: "8",
    src: require("./assets/banana.png"),
    x: 140,
    y: -30,
    height: 100,
    width: 100,
  },
  {
    id: "15",
    name: "baby bear",
    cost: "8",
    src: require("./assets/babyBear.png"),
    x: 240,
    y: 200,
    height: 130,
    width: 130,
  },
  {
    id: "16",
    name: "teen bear",
    cost: "8",
    src: require("./assets/teenbear.png"),
    x: 130,
    y: 140,
    height: 200,
    width: 120,
  },
];

export default images;
