const images = [
  {
    id: "1",
    name: "chain",
    cost: "5",
    src: require("./assets/chain.png"),
    x: 145,
    y: 100,
  },
  {
    id: "2",
    name: "propeller",
    cost: "10",
    src: require("./assets/propeller.png"),
    x: 150,
    y: -10,
  },
  {
    id: "3",
    name: "shades",
    cost: "4",
    src: require("./assets/shades.png"),
    x: 150,
    y: 0,
  },
  {
    id: "4",
    name: "nikes",
    cost: "8",
    src: require("./assets/nikes.png"),
  },
  {
    id: "5",
    name: "ironman",
    cost: "8",
    src: require("./assets/ironman.png"),
    x: 150,
    y: -10,
  },
  {
    id: "6",
    name: "bunnyears",
    cost: "8",
    src: require("./assets/bunnyears.png"),
  },
  {
    id: "7",
    name: "crown",
    cost: "8",
    src: require("./assets/crown.png"),
  },
  {
    id: "8",
    name: "bow",
    cost: "8",
    src: require("./assets/bow.png"),
  },
  {
    id: "9",
    name: "tie",
    cost: "8",
    src: require("./assets/tie.png"),
  },
  {
    id: "10",
    name: "fedora",
    cost: "8",
    src: require("./assets/fedora.png"),
  },
  {
    id: "11",
    name: "bandana",
    cost: "8",
    src: require("./assets/bandana.png"),
  },
  {
    id: "12",
    name: "batman",
    cost: "8",
    src: require("./assets/batman.png"),
  },
  {
    id: "13",
    name: "sneaker",
    cost: "8",
    src: require("./assets/sneaker.png"),
  },
  {
    id: "14",
    name: "banana",
    cost: "8",
    src: require("./assets/banana.png"),
  },
];

export default images;
